# SITE CONFIGURATION
url: "https://theoyuandawang.github.io"

author: Theoyuandawang
title:  theoyuandawang.github.io
logo:   header.png
description: "袁大网's life_repo"

excerpt_separator: "<!--more-->"

social:

  - icon:           twitter
    url:            https://twitter.com/Theoyuandawang
    description:    Twitter
  - icon:           github
    url:            https://github.com/theoyuandawang
    description:    Github
  - icon:           envelope
    url:            mailto:theoyuandawang@gmail.com
    description:    Email

permalink: /:year/:month/:title/

paginate: 16
paginate_path: "page/:num"
post_navigation: true

sass:
  sass_dir: _sass
  style: :compressed

exclude:
  - Gemfile
  - Gemfile.lock
